name: Update Amazon Deals

on:
  schedule:
    - cron: '0 * * * *' # Gira ogni ora esatta
  workflow_dispatch: # Permette di avviarlo manualmente per test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: python amazon_scraper.py
        env:
          PYTHONUNBUFFERED: 1

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add offerte.json
