name: Update Amazon Deals
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Setup
        run: |
          pip install playwright
          playwright install chromium
      - name: Run
        run: python amazon_scraper.py
      - name: Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add offerte.json
          git commit -m "Update" || exit 0
          git push
